---

- name: "Create directory"
  become_user: true
  file:
    path: ~/backend/
    state: directory

- name: "deploy backend"
  become_user: true
  unarchive:
    src: /etc/artifact.tar.gz
    dest: ~/backend/
    
- name: "run backend"
  become_user: true
  shell: |
    cd ~/backend/
    npm i
    pm2 start npm -- run start